# Application
quarkus.application.name=notification-worker
quarkus.http.port=4646

# Datasource - PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=pg-worker
quarkus.datasource.password=0706
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5445/pg-worker

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# Flyway
quarkus.flyway.migrate-at-start=true
spring.flyway.baseline-on-migrate=true

# Kafka
kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.low-stock-in.connector=smallrye-kafka
mp.messaging.incoming.low-stock-in.topic=inventory.low-stock
mp.messaging.incoming.low-stock-in.group.id=notification-worker
mp.messaging.incoming.low-stock-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.low-stock-in.auto.offset.reset=earliest
mp.messaging.incoming.low-stock-in.failure-strategy=ignore
